version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  fixme:
    enabled: true
  markdownlint:
    enabled: false
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
  phpmd:
    enabled: true
    config:
      rulesets: ".rulesets/rulesetPhpmd.xml"
  phan:
    enabled: false
    config:
      file_extensions: "php"
      checks:
      PhanUndeclaredClassMethod:
        enabled: false
exclude_patterns:
  - "public/"
  - "!public/index.php"
  - "tests/_reports/"
  - "storage/"
  - "vendor/"
